### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Gitrhuga** [azael1337/PHP-Discord-Token-Grabber#1]
I am hosting this on my on webiste. I replaced the webhook and uploaded it. It does not work

**Comment by K7ool222** [comment]
Same for me. 
It is not working at all !
I've been trying to find a fix but .... nothing

**Comment by BreadIsPan** [comment]
discord is patched this method.

**Comment by azael1337** [comment]
it's not supposed to work like that, it only works locally.
